import vpython

API_NAMES = [
    'Camera',
    'GSprint',
    'GSversion',
    'GlowWidget',
    'Mouse',
    'RackOutline',
    'RateKeeper',
    'ToothOutline',
    'acos',
    'acosh',
    'addpos',
    'adjust_axis',
    'adjust_up',
    'arange',
    'arrow',
    'asin',
    'asinh',
    'atan',
    'atan2',
    'atanh',
    'attach_arrow',
    'attach_trail',
    'baseObj',
    'box',
    'bumpmaps',
    'button',
    'canvas',
    'ceil',
    'checkbox',
    'clock',
    'color',
    'colorsys',
    'combin',
    'comp',
    'compound',
    'cone',
    'controls',
    'convert',
    'copysign',
    'cos',
    'cosh',
    'cross',
    'curve',
    'curveMethods',
    'cylinder',
    'cyvector',
    'degrees',
    'diff_angle',
    'distant_light',
    'dot',
    'e',
    'ellipsoid',
    'erf',
    'erfc',
    'event_return',
    'exp',
    'expm1',
    'extrusion',
    'fabs',
    'faces',
    'factorial',
    'floor',
    'fmod',
    'frame',
    'frexp',
    'fsum',
    'gamma',
    'gcd',
    'gcurve',
    'gdots',
    'ghbars',
    'gobj',
    'graph',
    'gs_version',
    'gvbars',
    'hat',
    'helix',
    'hypot',
    'inf',
    'isclose',
    'isfinite',
    'isinf',
    'isnan',
    'label',
    'ldexp',
    'lgamma',
    'list_to_vec',
    'local_light',
    'log',
    'log10',
    'log1p',
    'log2',
    'long',
    'mag',
    'mag2',
    'menu',
    'meta_canvas',
    'modf',
    'nan',
    'norm',
    'npdefault',
    'object_rotate',
    'path_object',
    'paths',
    'pi',
    'points',
    'pow',
    'print_anchor',
    'print_to_string',
    'proj',
    'pyramid',
    'quad',
    'radians',
    'radio',
    'random',
    'rate',
    'rate_control',
    'ring',
    'rotate',
    'rotatecp',
    'roundc',
    'scalecp',
    'scene',
    'shape_object',
    'shapes',
    'shapespaths',
    'simple_sphere',
    'sin',
    'sinh',
    'sleep',  # From vpython.py
    'slider',
    'sphere',
    'sqrt',
    'standardAttributes',
    'tan',
    'tanh',
    'tau',
    'text',
    'textures',
    'triangle',
    'trunc',
    'v',
    'vec',
    'vector',
    'version',
    'vertex',
    'wtext'
]


def test_names_in_base_namspace():
    current_names = set(name for name in dir(vpython)
                        if not name.startswith('_'))
    api_name_set = set(API_NAMES)
    print(sorted(api_name_set - current_names))

    # We may have added new names, so start with this weaker test
    assert api_name_set.issubset(current_names)

    # Ideally this test also passes -- everything in the API is what
    # we should expose and everything we expose is in the API.
    assert api_name_set == current_names
